version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres-scacchi
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chessdb
    ports:
      - "5432:5432"
    volumes:
      - chess-data:/var/lib/postgresql/data

volumes:
  chess-data:
